### ISSUE TITLE
No support for Magento 2.0.x?

### ISSUE THREAD

**Issue by skuda** [alexcheng1982/docker-magento2#14]
I checked here: https://hub.docker.com/r/alexcheng/magento2/tags/ but I can't find any 2.0.x version tag, there is any reason not to support 2.0.x? 

I am thinking of doing one myself to test our extension but it would be nicer if we can use your Docker image for all our tests.

Thanks!

**Comment by alexcheng1982** [comment]
I just added the 2.0.x branch. You can use the tag `2.0` for 2.0.x latest version `2.0.17`. There are also tags `2.0.9` and `2.0.17`.

**Comment by skuda** [comment]
thanks!
