### ISSUE TITLE
Custom Theme

### ISSUE THREAD

**Issue by steved1982** [alexcheng1982/docker-magento2#15]
I have a volume in my docker compose like this:
`- /dev/mytheme:/var/www/html/app/design/frontend/mytheme/default`
then in my local directory in the dev/mytheme folder I have the registration.php file to register a custom theme but when I go to the local admin area I am not seeing the custom theme. Have I missed a step?

Could you help.
Thanks

**Comment by Almusamim** [comment]
@steved1982 did you manage to work it out?

**Comment by noureddine-latreche** [comment]
try this put dot before ./dev like this:
`./dev/mytheme:/var/www/html/app/design/frontend/mytheme/default`
and after you do 
docker-compos up -d
try to explore your container and see is the theme has been copied
`docker exec -t -i [container_id] bash `
