### ISSUE TITLE
Module Development

### ISSUE THREAD

**Issue by jnrbo** [alexcheng1982/docker-magento2#17]
Hi there, how can I create a volume to Module development?

For example, using Docker's wordpress I can add at `docker-compose.yml`:

```
volumes:
       - ./plugins:/var/www/html/wp-content/plugins
```

And every plugin added to Wordpress will be accessible from **plugins folder**.

Do you know any way to do this in Magento2 using your Docker image?

**Comment by Morgy93** [comment]
You can easily include your own volume for development (which is still no fun then)

```
volumes:
      - ./local/path/to/your/module:/var/www/html/app/code/jnrbo/mymodule
      - ./local/path/to/your/theme:/var/www/html/app/frontend/jnrbo/mytheme
```
