### ISSUE TITLE
Install sample data failed on MAC

### ISSUE THREAD

**Issue by LarryBug** [alexcheng1982/docker-magento2#23]
MAC, 
docker Version 18.03.1-ce-mac65 (24312)
Compose: 1.21.1
Machine: 0.14.0

Refer your guide, execute the following query:
$docker exec -it docker-magento2_web_1 install-sampledata

ln: failed to create symbolic link '/var/www/html/var/composer_home/auth.json': File exists
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
-------
But after 20min, it's still stop here...
After review other issues, still cannot resolve this problem.

@alexcheng1982 If you have time, could you help me?

**Comment by LarryBug** [comment]
GFW.....

**Comment by timotheeguerinrb** [comment]
I have the same problem, what did you do to solve your issue ? Thanks
